### ISSUE TITLE
Transfer learning for different searching spaces

### ISSUE THREAD

**Issue by Yuz-Wang** [thomas-young-2013/open-box#54]
I have several similar tasks, but some parts of the searched parameters are different. Can I use the transfer learning in this case?

**Comment by salty-fish-97** [comment]
We are sorry that OpenBox does not support transfer learning on different spaces so far. The implementation is based 
on RGPE, which requires the history tasks sharing the same space. Please refer to [https://arxiv.org/pdf/1802.02219.pdf](url) for more details.

**Comment by Yuz-Wang** [comment]
Thanks for the replying. Could  you give an example of transfer learning.
