### ISSUE TITLE
Is there ask-and-tell interface?

### ISSUE THREAD

**Issue by McGinn7** [thomas-young-2013/open-box#55]
I have some evaluated hyperparameters and I want to know how to register these results to open-box.

I didn't find the demo, and it seems that I have to modify some code myself.

Could you give me some advice? Thank you ~

**Comment by salty-fish-97** [comment]
We implement `get_suggestion`(ask) and `update_observation` (tell) in the config_advisor of an optimizer. We are sorry that we do not have a demo showing how to register history to OpenBox so far. 

If you want to register evaluated configurations, we suggest trying the following codes. Here is a simple example of adding history to an optimizer before optimization:
```
from openbox import Optimizer
from openbox.core.base import Observation
from openbox.utils.constants import SUCCESS
from ConfigSpace import Configuration

config_space= ...
optimizer = Optimizer(...)
for config_array, perf in history: 
    config = Configuration(config_space, vector=config_array) # Make sure that config is an instance of ConfigSpace.Configuration
    trial_state = SUCCESS
    constraints = None
    objs = [perf] 
    elapsed_time = None
    observation = Observation(config, trial_state, constraints, objs, elapsed_time)
    optimizer.config_advisor.update_observation(observation)
optimizer.run()
```

**Comment by McGinn7** [comment]
> We implement `get_suggestion`(ask) and `update_observation` (tell) in the config_advisor of an optimizer. We are sorry that we do not have a demo showing how to register history to OpenBox so far.
> 
> If you want to register evaluated configurations, we suggest trying the following codes. Here is a simple example of adding history to an optimizer before optimization:
> 
> ```
> from openbox import Optimizer
> from openbox.core.base import Observation
> from openbox.utils.constants import SUCCESS
> from ConfigSpace import Configuration
> 
> config_space= ...
> optimizer = Optimizer(...)
> for config_array, perf in history: 
>     config = Configuration(config_space, vector=config_array) # Make sure that config is an instance of ConfigSpace.Configuration
>     trial_state = SUCCESS
>     constraints = None
>     objs = [perf] 
>     elapsed_time = None
>     observation = Observation(config, trial_state, constraints, objs, elapsed_time)
>     optimizer.config_advisor.update_observation(observation)
> optimizer.run()
> ```

Thank you very much!
