### ISSUE TITLE
How to disable the function to print information?

### ISSUE THREAD

**Issue by hzxwonder** [thomas-young-2013/open-box#59]
The project is wonderful! It helps me a lot! But I don't know how to disable the function to print information, i.e. 
![QQ截图20211108163253](https://user-images.githubusercontent.com/52537483/140709319-8e8f7ab7-e5d3-43b0-92d7-1ccd839a01e1.jpg)
I don't want to print the information which makes my results hard to observe. So is there any method to solve it?

**Comment by salty-fish-97** [comment]
Thanks for the issue! We apologize that there's no button to switch off the logging information so far. We will add a parameter to control the logger in the following version.

To solve the problem in the current version, we suggest:
1. Download the project.
2. Filter the information by modifying the configuration file `logging.yaml` under `openbox/utils/`.
![image](https://user-images.githubusercontent.com/32727236/140713157-a572d650-c87c-42e3-9341-68d186fc0276.png)
Change the logging level in Line 11 from `INFO` to `ERROR`. 
3. Uninstall the current version of OpenBox.
4. Run `python setup.py install` under the root directory of the project to reinstall OpenBox. 

In this way, all messages that start with `[INFO]` will be filtered.

**Comment by hzxwonder** [comment]
OK ，thank you for answering! Looking forward to your next version!
