### ISSUE TITLE
Warning in multi-objectives searching with constraints

### ISSUE THREAD

**Issue by Yuz-Wang** [thomas-young-2013/open-box#60]
The following is the configuration:

`opt = Optimizer(
		objective_function,
		space,
		num_objs=2,
		num_constraints=1,
		max_runs=500,
		surrogate_type='prf',  
		acq_type='ehvic',
		acq_optimizer_type='random_scipy',
		initial_runs=30,
		init_strategy='sobol',
		ref_point=ref_point_search,
		time_limit_per_trial=4000,
		random_state=1,
	)`

The warning prints in the iteration 31:
[openbox.acq_maximizer.ei_optimization_LocalSearch] Local search took already 1000 iterations. Is is maybe stuck in a infinite loop?

Is there anything wrong？

**Comment by salty-fish-97** [comment]
Thanks for you issue. However, this repo will be deprecated and will not be maintained anymore. The new location of OpenBox is [here](https://github.com/PKU-DAIR/open-box). Could raise the same issue in the new repo? We will help answer it in a few days.
