### ISSUE TITLE
Why can't the re-optimization method be applied to the single-objective optimization with constraints?

### ISSUE THREAD

**Issue by ganfoubudalian** [thomas-young-2013/open-box#61]

**Comment by salty-fish-97** [comment]
The re-optimization algorithm in OpenBox is a variant of [RGPE](https://arxiv.org/abs/1802.02219v1), which is a transfer learning method proposed only for single-objective problems without constraints. We refer to the original paper for more details about RGPE.

By the way, this repository is deprecated, and we will not update this repository any more. Please check [here](https://github.com/PKU-DAIR/open-box) to get the latest version of OpenBox.
